// purpose of this script:

// User clicks a button, then will be taken a random degreepage.

const degreepages = [
  "schoolofarchitecture/interiordesign-bsid.html",
  "schoolofarchitecture/architecture-barch.html",
  "schoolofarchitecture/architecture-architecturalengineering-barch-bsarche.html",
  "schoolofarchitecture/architecture-planiihonors-barch-ba.html",
  "schoolofarchitecture/architecturalstudies-bsas.html",
  "redmccombsschoolofbusiness/accounting-bba.html",
  "redmccombsschoolofbusiness/businessanalytics-bba.html",
  "redmccombsschoolofbusiness/businessadministration,honorstrack-bba.html",
  "redmccombsschoolofbusiness/finance-bba.html",
  "redmccombsschoolofbusiness/internationalbusiness-bba.html",
  "redmccombsschoolofbusiness/management-bba.html",
  "redmccombsschoolofbusiness/managementinformationsystems-bba.html",
  "redmccombsschoolofbusiness/marketing-bba.html",
  "redmccombsschoolofbusiness/supplychainmanagement-bba.html",
  "schoolofcivicleadership/civicshonors-ba.html",
  "moodycollegeofcommunication/advertising-bsadv.html",
  "moodycollegeofcommunication/communicationandleadership-bscomm&lead.html",
  "moodycollegeofcommunication/communicationstudies-bscommstds.html",
  "moodycollegeofcommunication/journalism-bj.html",
  "moodycollegeofcommunication/publicrelations-bspr.html",
  "moodycollegeofcommunication/radio-television-film-bsrtf.html",
  "moodycollegeofcommunication/speech,language,andhearingsciences-bsslh.html",
  "collegeofeducation/athletictraining-bsathtrng.html",
  "collegeofeducation/education-bsed.html",
  "collegeofeducation/youthandcommunitystudies-bsed.html",
  "collegeofeducation/appliedmovementscience-bskin&health.html",
  "collegeofeducation/exercisescience-bskin&health.html",
  "collegeofeducation/healthpromotionandbehavioralscience-bskin&health.html",
  "collegeofeducation/physicalcultureandsportsstudies-bskin&health.html",
  "collegeofeducation/sportmanagement-bskin&health.html",
  "cockrellschoolofengineering/aerospaceengineering-bsase.html",
  "cockrellschoolofengineering/architecturalengineering-bsarche.html",
  "cockrellschoolofengineering/biomedicalengineering-bsbiomede.html",
  "cockrellschoolofengineering/chemicalengineering-bsche.html",
  "cockrellschoolofengineering/civilengineering-bsce.html",
  "cockrellschoolofengineering/computationalengineering-bscompe.html",
  "cockrellschoolofengineering/electricalandcomputerengineering-bsece.html",
  "cockrellschoolofengineering/environmentalengineering-bsenve.html",
  "cockrellschoolofengineering/geosystemsengineering-bsge.html",
  "cockrellschoolofengineering/mechanicalengineering-bsme.html",
  "cockrellschoolofengineering/petroleumengineering-bspe.html",
  "collegeoffinearts/acting-bfa.html",
  "collegeoffinearts/arteducation-bfa.html",
  "collegeoffinearts/dance-bfa.html",
  "collegeoffinearts/design-bfa.html",
  "collegeoffinearts/studioart-bfa.html",
  "collegeoffinearts/theatreeducation-bfa.html",
  "collegeoffinearts/composition-bmusic.html",
  "collegeoffinearts/jazz-bmusic.html",
  "collegeoffinearts/musicperformance-bmusic.html",
  "collegeoffinearts/musicstudies-bmusic.html",
  "collegeoffinearts/arthistory-ba.html",
  "collegeoffinearts/design-ba.html",
  "collegeoffinearts/studioart-ba.html",
  "collegeoffinearts/theatreanddance-batd.html",
  "collegeoffinearts/music-bamusic.html",
  "collegeoffinearts/artsandentertainmenttechnologies-bsaet.html",
  "johna.andkatherineg.jacksonschoolofgeosciences/geosciences-bags.html",
  "johna.andkatherineg.jacksonschoolofgeosciences/geosciences-bsenvirsci.html",
  "johna.andkatherineg.jacksonschoolofgeosciences/climatesystemscience-bsgs.html",
  "johna.andkatherineg.jacksonschoolofgeosciences/generalgeology-bsgs.html",
  "johna.andkatherineg.jacksonschoolofgeosciences/geophysics-bsgs.html",
  "johna.andkatherineg.jacksonschoolofgeosciences/geosciences-bsgs.html",
  "johna.andkatherineg.jacksonschoolofgeosciences/hydrologyandwaterresources-bsgs.html",
  "johna.andkatherineg.jacksonschoolofgeosciences/geosystemsengineering-bsge.html",
  "schoolofinformation/informatics-ba.html",
  "schoolofinformation/informatics-bsi.html",
  "collegeofliberalarts/africanandafricandiasporastudies-ba.html",
  "collegeofliberalarts/americanstudies-ba.html",
  "collegeofliberalarts/anthropology-ba.html",
  "collegeofliberalarts/asianculturesandlanguages-ba.html",
  "collegeofliberalarts/asianstudies-ba.html",
  "collegeofliberalarts/classicallanguages-ba.html",
  "collegeofliberalarts/classicalstudies-ba.html",
  "collegeofliberalarts/economics-ba.html",
  "collegeofliberalarts/english-ba.html",
  "collegeofliberalarts/ethnicstudies-ba.html",
  "collegeofliberalarts/europeanstudies-ba.html",
  "collegeofliberalarts/frenchstudies-ba.html",
  "collegeofliberalarts/geography-ba.html",
  "collegeofliberalarts/german-ba.html",
  "collegeofliberalarts/government-ba.html",
  "collegeofliberalarts/healthandsociety-ba.html",
  "collegeofliberalarts/history-ba.html",
  "collegeofliberalarts/humandimensionsoforganizations-ba.html",
  "collegeofliberalarts/humanities-ba.html",
  "collegeofliberalarts/internationalrelationsandglobalstudies-ba.html",
  "collegeofliberalarts/italianstudies-ba.html",
  "collegeofliberalarts/jewishstudies-ba.html",
  "collegeofliberalarts/latinamericanstudies-ba.html",
  "collegeofliberalarts/linguistics-ba.html",
  "collegeofliberalarts/mexicanamericanandlatina-ostudies-ba.html",
  "collegeofliberalarts/middleeasternstudies-ba.html",
  "collegeofliberalarts/philosophy-ba.html",
  "collegeofliberalarts/psychology-ba.html",
  "collegeofliberalarts/race,indigeneity,andmigration-ba.html",
  "collegeofliberalarts/religiousstudies-ba.html",
  "collegeofliberalarts/rhetoricandwriting-ba.html",
  "collegeofliberalarts/russian,easteuropean,andeurasianstudies-ba.html",
  "collegeofliberalarts/sociology-ba.html",
  "collegeofliberalarts/spanish-ba.html",
  "collegeofliberalarts/sustainabilitystudies-ba.html",
  "collegeofliberalarts/urbanstudies-ba.html",
  "collegeofliberalarts/women'sandgenderstudies-ba.html",
  "collegeofliberalarts/planiihonorsprogram-ba.html",
  "collegeofliberalarts/behavioralandsocialdatascience-bsbsds.html",
  "collegeofliberalarts/economics-bseco.html",
  "collegeofliberalarts/geographicalsciences-bsenvirsci.html",
  "collegeofliberalarts/psychology-bspsy.html",
  "collegeofnaturalsciences/astronomy-ba.html",
  "collegeofnaturalsciences/chemistry-ba.html",
  "collegeofnaturalsciences/mathematics-ba.html",
  "collegeofnaturalsciences/physics-ba.html",
  "collegeofnaturalsciences/astronomy-bsa.html",
  "collegeofnaturalsciences/biology-bsa.html",
  "collegeofnaturalsciences/chemistry-bsa.html",
  "collegeofnaturalsciences/computerscience-bsa.html",
  "collegeofnaturalsciences/humandevelopmentandfamilysciences-bsa.html",
  "collegeofnaturalsciences/humanecology-bsa.html",
  "collegeofnaturalsciences/mathematics-bsa.html",
  "collegeofnaturalsciences/neuroscience-bsa.html",
  "collegeofnaturalsciences/nutrition-bsa.html",
  "collegeofnaturalsciences/physics-bsa.html",
  "collegeofnaturalsciences/astronomy-bsast.html",
  "collegeofnaturalsciences/biochemistry-bsbioch.html",
  "collegeofnaturalsciences/biology-bsbio,microbiologyandinfectiousdiseases.html",
  "collegeofnaturalsciences/chemistry-bsch.html",
  "collegeofnaturalsciences/computerscience-bscompsci.html",
  "collegeofnaturalsciences/biologicalsciences-bsenvirsci.html",
  "collegeofnaturalsciences/humandevelopmentandfamilysciences-bshdfs.html",
  "collegeofnaturalsciences/mathematics-bsmath.html",
  "collegeofnaturalsciences/medicallaboratoryscience-bsmedlabsci.html",
  "collegeofnaturalsciences/neuroscience-bsneurosci.html",
  "collegeofnaturalsciences/nutrition-bsntr.html",
  "collegeofnaturalsciences/physics-bsphy.html",
  "collegeofnaturalsciences/publichealth-bspublichealth.html",
  "collegeofnaturalsciences/statisticsanddatascience-bssds.html",
  "collegeofnaturalsciences/textilesandapparel-bsta.html",
  "schoolofnursing/nursing-bsn.html",
  "lyndonb.johnsonschoolofpublicaffairs/publicaffairs-bapubaff.html",
  "stevehicksschoolofsocialwork/socialwork-bsw.html",
];

randombutton = document.getElementById("randompagebutton");

function gotorandompage(e) {
  e.preventDefault(); // Prevent default link behavior

  // math.floor gets floor. Math.random returns float between 0 and 1.
  const randomIndex = Math.floor(Math.random() * degreepages.length);
  const randomPage = degreepages[randomIndex];

  // need to use window change to make the entire button clickable
  window.location.href = randomPage;
}

// e means event handling
randombutton.addEventListener("click", gotorandompage);
